import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLocale } from "gt-next/server";
import { GTProvider, LocaleSelector } from "gt-next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children


}: Readonly<{children: React.ReactNode;}>) {
  return (
  <html

    className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} lang={await getLocale()}>
    
      <body className="min-h-full flex flex-col">
        <GTProvider>
          <header className="flex items-center justify-end px-6 py-3">
            <LocaleSelector />
          </header>
          {children}
        </GTProvider>
      </body>
    </html>
  );
}